const action = {
  CREATE_PROJECT: 'CREATE_PROJECT',
  CHANGE_SELECTION: 'CHANGE_SELECTION',
  COPY: 'COPY',
  PASTE: 'PASTE',
  PRE_PUSH: 'PRE_PUSH',
  command: {
    NEW_EMPTY_SENTENCE: 'COMMAND_NEW_EMPTY_SENTENCE',
    NEW_SENTENCE: 'COMMAND_NEW_SENTENCE',
    DELETE: 'COMMAND_DELETE',
    CHANGE_COMBO_INDEX: 'COMMAND_CHANGE_COMBO_INDEX',
    CHANGE_SENTENCE: 'COMMAND_CHANGE_SENTENCE',
    UNDO: 'COMMAND_UNDO',
    REDO: 'COMMAND_REDO',
  },
};
export default action;
