const action = {
  CREATE_PROJECT: 'CREATE_PROJECT',
  CHANGE_SELECTION: 'CHANGE_SELECTION',
  COPY: 'COPY',
  PASTE: 'PASTE',
  command: {
    NEW_EMPTY_SENTENCE: 'NEW_EMPTY_SENTENCE',
    NEW_SENTENCE: 'NEW_SENTENCE',
    MULTIPLE_NEW_SENTENCE: 'MULTIPLE_NEW_SENTENCE',
    DELETE: 'DELETE',
    MULTIPLE_DELETE: 'MULTIPLE_DELETE',
    DELETE_SELECTED: 'DELETE_SELECTED',
  },
};
export default action;
