const mutation = {
  CHANGE_PROJECT_NAME: 'CHANGE_PROJECT_NAME',
  CHANGE_PROJECT_SEED: 'CHANGE_PROJECT_SEED',
  CHANGE_PROJECT_VIDEOS: 'CHANGE_PROJECT_VIDEOS',
  NEW_SENTENCE: 'NEW_SENTENCE',
  REMOVE: 'REMOVE',
  CHANGE_COMBO_INDEX: 'CHANGE_COMBO_INDEX',
  ADD_SELECTED: 'ADD_SELECTED',
  REMOVE_SELECTED: 'REMOVE_SELECTED',
  RESET_SELECTED: 'RESET_SELECTED',
  COPY_SELECTED: 'COPY_SELECTED',
  CHANGE_SENTENCE: 'CHANGE_SENTENCE',
  EVALUATE_SELECTED: 'EVALUATE_SELECTED',
};

export default mutation;
