const mutation = {
  CHANGE_PROJECT_NAME: 'CHANGE_PROJECT_NAME',
  CHANGE_PROJECT_SEED: 'CHANGE_PROJECT_SEED',
  CHANGE_PROJECT_VIDEOS: 'CHANGE_PROJECT_VIDEOS',
  PUSH_SENTENCE: 'PUSH_SENTENCE',
  PUSH_EMPTY_SENTENCE: 'PUSH_EMPTY_SENTENCE',
  PUSH_TOP_EMPTY_SENTENCE: 'PUSH_TOP_EMPTY_SENTENCE',
  REMOVE: 'REMOVE',
  CHANGE_COMBO_INDEX: 'CHANGE_COMBO_INDEX',
  CHANGE_MENU_ACTION: 'CHANGE_MENU_ACTION',
};

export default mutation;
